import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'
import Header from '@/components/site-header'
import Footer from '@/components/site-footer'

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat',
})

export const metadata: Metadata = {
  title: 'Pesantren Kota Malang',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="light">
      <body className={montserrat.className}>
        <Header />
        <div className="px-28">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  )
}
